### ISSUE TITLE
Thanks for creating this project!

### ISSUE THREAD

**Issue by rudolfolah** [BasioMeusPuga/Lector#10]
In 2018, the choices for desktop app creation seem to be...Electron. Thanks for using Qt and thanks just for creating a cool free/open source software project. Wanted to get some thanks in before you're hit with a ferocious list of real issues ;)

**Comment by BasioMeusPuga** [comment]
Let's hope it's more of a "gently swaying in the wind" list of real issues. :)

I'm glad you like it. More importantly, I'm glad you find it useful.
