### ISSUE TITLE
Page by page view

### ISSUE THREAD

**Issue by d5ve** [BasioMeusPuga/Lector#102]
I'm not sure if I'm just missing this, but is there a setting for a paged view?

By this I mean more like a physical book, where you read an entire page, then turn to read the next, rather than scrolling continuously through the book. 

I find it easier to keep my place with paging, rather than scrolling.

Thanks for this neat ebook reader.

**Comment by BasioMeusPuga** [comment]
There's a single page view you can access through a right click. I'm working on a double page view (as you will see from that context menu), but that will take a little time since it's going to involve a significant refactor and I'm currently on a break due to IRL reasons.

**Comment by wadbr** [comment]
Sorry about this but where should I right click to get this? In book view I'm only getting search/add bookmark.

I'm running version 0.5.1 on Win64 and Python 3.7

**Comment by andrewchenshx** [comment]
double page view does NOT work.
environment: win 10 64bit, python 3.7.3 (ananconda)
error message:
Traceback (most recent call last):
  File "C:\Users\Andrew\Documents\GitHub\Lector\lector\contentwidgets.py", line 877, in generate_textbrowser_context_menu
    self.create_pages('doublePages')
  File "C:\Users\Andrew\Documents\GitHub\Lector\lector\contentwidgets.py", line 591, in create_pages
    self.set_page(cursorTop)
  File "C:\Users\Andrew\Documents\GitHub\Lector\lector\contentwidgets.py", line 633, in set_page
    cursorGoTo.setPosition(page_start)
UnboundLocalError: local variable 'page_start' referenced before assignment
