### ISSUE TITLE
How can I uninstall it?

### ISSUE THREAD

**Issue by CavaleriOmar** [BasioMeusPuga/Lector#108]
As much as I like a lot the program I would like to know, in the eventuality it doesn't satisfy my needs anymore, what should I do to uninstall it from my system.

I'm on KDE Neon 5.16

**Comment by BasioMeusPuga** [comment]
You can remove all the files in the `install.txt` file that's in the directory you cloned the repo to. Alternatively, remove the binary from `/usr/bin` or whatever Neon uses, and the corresponding directory from `/usr/lib/pythonX.X/site-packages/lector...`

**Comment by CavaleriOmar** [comment]
Thanks
