### ISSUE TITLE
Add AppStream metainfo files to support Linux software stores

### ISSUE THREAD

**Issue by terrycloth** [BasioMeusPuga/Lector#118]
Most GNU/Linux distributions nowadays have a GUI application for browsing available software packages, such as GNOME Software, KDE Discover, etc... Software and Discover (and all the distro-specific app stores based on them) have settled on the XML-based [AppStream specification](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps) for describing packages and including screenshots of the package's current GUI design. This gives you a nicer looking page on the "app store".

Lector already has some good screenshots, so all distribution packagers still need would be the XML files. I'm working on packaging Lector for Fedora right now, so I can create the AppData for you, but it will make things easier for packagers of other Linux distributions if you kept it here in the source repository. So I thought I'd mention this to you and see if you have any questions before putting together the AppData and sending you a pull request.

**Comment by BasioMeusPuga** [comment]
Thank you for the work. Please make a pull request and I'll merge it.

**Comment by BasioMeusPuga** [comment]
I've merged the pull request. Again, thank you for the work. I'l make updates to the file at the time of the next release.
