### ISSUE TITLE
Sort By "Last Read" only show read books

### ISSUE THREAD

**Issue by delfino-nunez** [BasioMeusPuga/Lector#12]
I don't know if this could be a bug, but if all the options in "sort by" drop down show all the books except the option "Last read", I don't know if this could confusing because only shows read books and not the unread.

Features request: 
If I sort it by "Last read" would be nice to show the last read date.
Also in the "table" view doesn't show the "Last read" column for sorting.

**Comment by BasioMeusPuga** [comment]
This is on purpose. "Last read" has no meaning for an unread book. Therefore, books will not be displayed in case they haven't been touched. This will just add clutter.

That column is addable though. Should be in the code soon.

**Comment by BasioMeusPuga** [comment]
I've added the column. And a few other things. I guess we'll be having a "OH GOD YOU BROKE THIS?" conversation shorty.
