### ISSUE TITLE
Cannot use annotator and search option [Ubuntu 18.04]

### ISSUE THREAD

**Issue by SumanRoyGhatak** [BasioMeusPuga/Lector#129]
After installing Lector today, I opened a pdf file with it. But I cannot use the annotator and the search option, although they show the names of icons and their shortcuts, Ctrl+N and Ctrl+F respectively. The shortcuts aren't working either. I need to use the annotator frequently for scientific texts. Help please.

**Comment by BasioMeusPuga** [comment]
I'm afraid pdf files are rendered as images. So there's very little by way of annotation or searching there. I would recommend `okular`. It's one of the best pdf readers and annotators I've tried.
