### ISSUE TITLE
Table view column "%" doesn't show the % value, only a graph

### ISSUE THREAD

**Issue by delfino-nunez** [BasioMeusPuga/Lector#13]
I think it would be nice to show the % value with the graph or without it.

**Comment by BasioMeusPuga** [comment]
This is a design decision. The Table view, where there's enough clutter as it is, is the only place where this might be visible.
Also, the pie chart thingy is admittedly wildly inaccurate in that it currently only tracks chapters and not lines. Won't add anything but I will get people going "I read 15 lines why am I stuck at 23% literally unusable".

I *might* do this if the line tracking thing is relatively cheap.
