### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by fitojb** [BasioMeusPuga/Lector#16]
I’d love to share this application with my friends, but there appears to be no support for internationalization. Could this be added eventually?

**Comment by BasioMeusPuga** [comment]
Absolutely. Much sooner than "eventually", too. This seems like a relatively high priority thing to do.

**Comment by BasioMeusPuga** [comment]
I've implemented support for translations. I'll put instructions about how to contribute in the README shortly. In the meantime, you'll find untouched .ts files in `/resources/translations`. 

Just open any of those with qt linguist and set to a language of your choosing. Then send the file back to me. That's about it.

**Comment by fitojb** [comment]
Thanks so much! Here it is: 
[Lector_es.zip](https://github.com/BasioMeusPuga/Lector/files/1824262/Lector_es.zip)

**Comment by BasioMeusPuga** [comment]
Great. I've integrated the translation into the program. See if it's showing up?

**Comment by fitojb** [comment]
Yep, they show up for me. Thanks!
