### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by xa0** [BasioMeusPuga/Lector#17]
It's possible to have ctrl + o shortcut to add books?
And up/down keys in the pdf parser?

Thanks for all your work.

**Comment by BasioMeusPuga** [comment]
Of course. They're fairly easy to implement too. Give me a commit or two.

**Comment by BasioMeusPuga** [comment]
This is done. Do tell me if you think some other keyboard shortcuts are warranted.
