### ISSUE TITLE
poppler-qt5 again

### ISSUE THREAD

**Issue by bsbhro** [BasioMeusPuga/Lector#21]
Hi, I tried a lot, but pdf-support doesn't work. All requirements are installed, I think...
![bildschirmfoto_2018-03-18_19-24-03](https://user-images.githubusercontent.com/2652120/37569441-865e1348-2ae2-11e8-83a1-ba27914f5c0e.png)
Any hints for me? Thank you!

**Comment by BasioMeusPuga** [comment]
Do you also have `poppler-qt5` installed (at about the version specified in the README)?

**Comment by bsbhro** [comment]
After installing Qt5 from their very slow server and no success I read your edit. This Memory access violation I mentioned some hours before too.
![bildschirmfoto_2018-03-18_22-23-14](https://user-images.githubusercontent.com/2652120/37571324-a2fda446-2afb-11e8-86b1-bba8c58a1e06.png)
What could this be? It's a new experience for me to install a python programm :-)

**Comment by BasioMeusPuga** [comment]
My German is a little rusty. Which is to say I don't know any. But that reads as a segmentation fault.

Some googling leads me to the following:
https://github.com/wbsoft/frescobaldi/issues/838#issuecomment-251867781

Try `pip show sip python-poppler-qt5` in a terminal and tell me what versions you have installed.

**Comment by bsbhro** [comment]
Hi, Good Morning,
Memory access is 'Speicherzugriff'... pip doesn't output anything, but pip3 does.
![bildschirmfoto_2018-03-19_08-50-42](https://user-images.githubusercontent.com/2652120/37584364-77dd72e6-2b55-11e8-91a9-2313e51b24b9.png)
I tried intalling poppler with pip; only pip3 goes.
![bildschirmfoto_2018-03-19_08-54-05](https://user-images.githubusercontent.com/2652120/37584467-e57bbb46-2b55-11e8-89e7-f231e3289b91.png)

There is another software here on github: arminstraub/krop. Same problem!
Thanks

**Comment by ShadowMitia** [comment]
Hi,

I got the same error, but when I try to import popplerqt5 in the terminal it gives me this:
```
>>> import popplerqt5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /lib64/libQt5Core.so.5: version `Qt_5.10' not found (required by /usr/local/lib64/python3.6/site-packages/PyQt5/QtCore.so)
>>> 

```

And my version of Qt5 installed from my package manager (I'm using Fedora), is still on 5.9.*, which explains the error.

Hope this helps.

**Comment by bsbhro** [comment]
It's a pity, but after an install orgy (all from source; qt5, sip, poppler) it ended with an undefined QDomElement. I stop here.

**Comment by BasioMeusPuga** [comment]
I really don't think the error is with Lector here. That said, I'll try to make a Flatpak available at around the time of the .3 release. That should workaround what issues you have.
