### ISSUE TITLE
Is Windows supported by some development version

### ISSUE THREAD

**Issue by Marlysson** [BasioMeusPuga/Lector#33]
I've tried install the dependencies and I fails in do that by some dependencies like ( sipdistutils ) don't install.

**Comment by BasioMeusPuga** [comment]
I'm having trouble getting python-poppler-qt5 installed on Windows myself. I'll work on getting a Windows installer ready for 1.0.
However, if pdf support isn't that important to you, everything else runs fine.

Just use `pip` to install `pyqt5`, `beautifulsoup4`, and `lxml`. Launch with `__main__.py`

**Comment by Marlysson** [comment]
I've install the libraries and appears this error:

```python-poppler-qt5 is not installed. Pdf files will not work.
Locale: pt_BR (No translations found)
Database: No paths for settings...
Available parsers: *.pdf *.epub *.mobi *.azw *.azw3 *.azw4 *.prc *.cbz *.cbr
Database returned nothing
Traceback (most recent call last):
  File "__main__.py", line 392, in add_books
    self.reloadLibrary.setEnabled(False)
AttributeError: 'MainUI' object has no attribute 'reloadLibrary'
```

**Comment by BasioMeusPuga** [comment]
You're not at the latest commit. I fixed this yesterday.
