### ISSUE TITLE
uninstalll Lector

### ISSUE THREAD

**Issue by mich2018** [BasioMeusPuga/Lector#35]
How can i unistall LECTOR?

**Comment by BasioMeusPuga** [comment]
How did you install it in the first place?

**Comment by mich2018** [comment]
Downloaded "Lector-master" folder and typed
 $ python setup.py build
 # python setup.py install

**Comment by BasioMeusPuga** [comment]
Do you have an `install.txt` in the directory you typed this in?

Try this: `sudo rm $(cat install.txt)`

**Comment by mich2018** [comment]
I used the code below and i think it worked ! 

#!/bin/bash
while read -r line; do
  rm $line && echo $line
done < install.txt

**Comment by BasioMeusPuga** [comment]
Of course. It's basically the same thing. I'm going to close this now. Let me know if you need help with the other issue.

**Comment by mich2018** [comment]
by the way your program is using python3.6 but the default setup uses python2.7!!

took me time to figure that out, sadly i can run only Lectur or hplip on my system and Lecture popler-pt5 is not avialable

**Comment by BasioMeusPuga** [comment]
That's what I said in the other issue you opened. You don't *need* python-poppler-qt5 if you don't want pdf support. I'm trying to find a way to bundle it though.
