### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by csrgxtu** [BasioMeusPuga/Lector#39]
```bash
python __main__.py

  File "__main__.py", line 387
    f'{ebooks_string} ({self.available_parsers})')
                                                ^
SyntaxError: invalid syntax


```

**Comment by BouncePrime** [comment]
Running with python3 is not helping [neither with python 2]
![screenshot from 2018-05-19 23-17-45](https://user-images.githubusercontent.com/39442192/40271448-152ac95a-5bbb-11e8-8d07-ff23c91de864.png)
