### ISSUE TITLE
Dupilcated keyboard binding behavior for arrow keys in reader view

### ISSUE THREAD

**Issue by bugzy** [BasioMeusPuga/Lector#45]
Currently the key bindings for the arrow keys behave the same in the reader view; that is, "left" and "right" arrow keys behave the same as "up" and "down" arrow keys. It will probably work better if the if the "up" and "down" arrow keys are used for scrolling up and down, while the lef and right keys remain the same as they are now.

**Comment by BasioMeusPuga** [comment]
Left and Right switch chapters backwards and forwards, respectively. I assume you were using them at the start / end of a chapter. Then the behaviour would be similar, yes.

As far as the rest of the issues you've filed go, I'll get to them. I have a lot of stuff to attend to IRL right now, so it'll be in bits and pieces.
