### ISSUE TITLE
Using the search bar doesn't seem to work

### ISSUE THREAD

**Issue by maxigaz** [BasioMeusPuga/Lector#53]
With the latest git version installed via the [AUR](https://aur.archlinux.org/packages/lector-git/) package on Manjaro Linux, I have an issue that I can reproduce with the following steps:

1. Open an epub book, such as [A Byte of Python](https://www.gitbook.com/download/epub/book/swaroopch/byte-of-python).
1. Type the word "Python" into the search bar, hit Enter.
1. Nothing happens, even when I'm on a page/chapter that contains the word "Python".

**Comment by BasioMeusPuga** [comment]
This is to be expected since I haven't written the code yet. :)
I have it planned for 0.5 since pdf searching is proving to be a matter of some contention.
