### ISSUE TITLE
ModuleNotFoundError: No module named 'sipdistutils'

### ISSUE THREAD

**Issue by ThompkWT** [BasioMeusPuga/Lector#58]
How did you get sipdistutils installed for Mac.

None of the normal methods work for me.

pip install sip doesn't install sipdistutils

Thanks

Tilt Thompkind

**Comment by BasioMeusPuga** [comment]
What are you trying to do that requires `sipdistutils`? It's not listed as a dependency.

**Comment by ThompkWT** [comment]
thank you
