### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by xa0** [BasioMeusPuga/Lector#6]
```
$ python3.6 __main__.py 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-user'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-user'
Database returned no paths for settings...
Traceback (most recent call last):
  File "__main__.py", line 1197, in <module>
    main()
  File "__main__.py", line 1190, in main
    form = MainUI()
  File "__main__.py", line 76, in __init__
    self.metadataDialog = MetadataUI(self)
  File "/home/user/Lector/metadatadialog.py", line 41, in __init__
    mask = QtGui.QRegion(path.toFillPolygon().toPolygon())
TypeError: toFillPolygon(self, QTransform): not enough arguments
```

PyQt5 5.8.2

**Comment by BasioMeusPuga** [comment]
I can't replicate this at all. Could you please upgrade Qt and PyQt5 to 5.10.1 and see if it still persists? IIRC, The 5.8 and 5.9 releases were pretty rough.

**Comment by BasioMeusPuga** [comment]
Or if that isn't an option, just comment out the following lines from `metadatadialog.py` and `definitionsdialog.py`

    radius = 15
    path = QtGui.QPainterPath()
    path.addRoundedRect(QtCore.QRectF(self.rect()), radius, radius)
    mask = QtGui.QRegion(path.toFillPolygon().toPolygon())
    self.setMask(mask)

They should be around lines 35-40.

**Comment by xa0** [comment]
Thanks. It works with PyQt 5.10.1 :smiley:
Maybe there can be a note about it.
