### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Kuchiriel** [BasioMeusPuga/Lector#62]
Cool project brow, I see, there is this version on AUR lector-git. Can you make a lector-bin version of this and submit to AUR?

**Comment by BasioMeusPuga** [comment]
This is Python so there's nothing to compile, really. The install shouldn't take more than a few seconds.
Do you mean a package for the release version?

**Comment by Kuchiriel** [comment]
Yep, for the release version.

**Comment by BasioMeusPuga** [comment]
Sorry about the delay. Life has been hectic lately. You'll find a release package [here](https://aur.archlinux.org/packages/lector/).
