### ISSUE TITLE
Be able to change background color from "Define" dialog

### ISSUE THREAD

**Issue by edvm** [BasioMeusPuga/Lector#65]
It would be great to be able to change background color from the "Define" dialog, ex:
![screenshot from 2018-06-06 13-41-17](https://user-images.githubusercontent.com/689275/41052556-7810077e-698f-11e8-91b0-78d992f88523.png)
I was able to update font color, but didnt find a way to select the background color.

**Comment by BasioMeusPuga** [comment]
Hey, the button on the bottom right of the dialog should let you change the background color of the Define / Metadata dialogs. Does that not work for you?

**Comment by edvm** [comment]
![image](https://user-images.githubusercontent.com/689275/41056796-aad24cba-699b-11e8-80f8-58ba9143b20a.png)
It worked fiine, sorry! (dont know the first time i tryed that option). Then this issue seems to be invalid.
