### ISSUE TITLE
fb2 support

### ISSUE THREAD

**Issue by antmak** [BasioMeusPuga/Lector#66]
A small request, please add a fb2 support. Including .fb2.zip files

Thanks

**Comment by BasioMeusPuga** [comment]
Gladly. Can you please link me to ab .fb2 file? Something I can use to get started with?

**Comment by antmak** [comment]
I am glad to help! I've uploaded .fb2.zip example here https://gitlab.com/snippets/1722408 
Also you could unzip it to get pure .fb2 file

Many mobile readers understand .fb2.zip format but no one on the desktop

**Comment by BasioMeusPuga** [comment]
So we should have working fb2 support. Please tell me if you can get it to read the files you have.

**Comment by antmak** [comment]
I'm sorry my distro don't have update of lector yet. I plan to try it from git as I'll have a time

**Comment by lockedshadow** [comment]
Perhaps the specifications of fb2 format would be also interesting? You can find it here: https://github.com/gribuser/fb2.
And Calibre e-book management tool that also written in Python has implementation of fb2 reader/parser too. You can find source code here: https://github.com/kovidgoyal/calibre.

**Comment by BasioMeusPuga** [comment]
@wwwwwwww1 Were these files working earlier? I have made a few changes, so can you link me to a copy of a book that's not working?

**Comment by wwwwwwww1** [comment]
Any fb2 book from ponyfiction.org. Also don't open epub. [For example, wget](https://s4.speed4up.com/cgi-bin/dl.cgi/h2chvzeevsuohjzl3bniwriuvpvzlgpqkqp6z3kpv2oiyxzjbq5njai/Demon%20Rogue.epub)
           
[Launch in terminal](https://pastebin.com/7spM9suh)
          
How to more details?

**Comment by BasioMeusPuga** [comment]
I can't replicate this here. So I'd recommend a clean clone, and removal of the database / conflig files in `~/.local/share/Lector` and `~/.config/Lector` and restarting. You can also maybe check if `python-lxml` is installed.

In the meantime, I'm working on getting logging functional. That should allow me to diagnose things better.

**Comment by wwwwwwww1** [comment]
Thanks for tip. python-lxml was installed with errors. After reinstalling this package with pip3 it all worked. But there are problems. Do not added books from ponyfiction.

Check it, please. [Book](https://ponyfiction.org/story/13641/download/Vse_tsveta_zhizni.fb2) was added successful, but few problems. I downloaded this book again and it don't open.

And [this](https://ponyfiction.org/story/7192/download/Klopfik_nazvaniya_k_kotoromu_my_ne_pridumali.fb2). Not add.

**Comment by Carmina16** [comment]
The error with _Vse tsveta..._ is caused by this line:
https://github.com/BasioMeusPuga/Lector/blob/5e3987dc0426e6a28d248ab6725eefe96dffa0aa/lector/readers/read_fb2.py#L79

FB2 files can have no attachments or cover, so easiest way to fix it is also catching the `TypeError` exception.

@wwwwwwww1  The other file looks OK, what are your problems with it?

**Comment by BasioMeusPuga** [comment]
Yes. That was an oversight on my part. I've fixed it now.

If you need anything else, please consider creating a new issue so I can track thing better.
