### ISSUE TITLE
DJVU support

### ISSUE THREAD

**Issue by rrittwikc** [BasioMeusPuga/Lector#68]
Lector supports almost all the formats I have and more. For me the only format that Lector does not support is DJVU. Could you please add DJVU support?

You may look up DJVULibre [here](http://djvu.sourceforge.net/index.html). DJVULibre is a librery that parses DJVU files.

**Comment by BasioMeusPuga** [comment]
Of course. Could you please link me to a sample djvu file?

**Comment by rrittwikc** [comment]
Sure. Please download it from [here](http://djvu.org/docs/2001_compression_overview.djvu).

**Comment by BasioMeusPuga** [comment]
DjVu support is in the latest commit. Please let me know if it works.
