### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by psikoz** [BasioMeusPuga/Lector#70]
Hey @BasioMeusPuga 

I designed a logo for contribution. Logo idea

- book icon ( v form )
- cut corner = QT logo
- Letter L = the first letter of your application.

WDYT?

![lector](https://user-images.githubusercontent.com/40601249/42464256-323f527c-83b1-11e8-888c-a8368b032ec4.jpg)

**Comment by BasioMeusPuga** [comment]
Hey,

Thanks for your work. I especially like the ones in the right column. Especially 4 and 6.
If you're willing to send me these in a format without a background, I'll see that they make their way into the README and the About page, with attributions to you.
I'm happy with the icon we currently have, but if you'd like to polish that, be my guest.

**Comment by psikoz** [comment]
I think number 6 is more minimalist and compatible. That's why I sent you a pr.if you want, you can merge it.
