### ISSUE TITLE
Fedora 29

### ISSUE THREAD

**Issue by hhlp** [BasioMeusPuga/Lector#75]
fedora 29 is on the way are you going to continue with the project in fedora 29

regards.,

**Comment by BasioMeusPuga** [comment]
I've been really busy with real life.  I'll get back to active dev as soon as I get time.
There's no reason the application won't work in Fedora 29, though. Is there some reason you ask?

**Comment by BasioMeusPuga** [comment]
Yeah, that's a packaging issue.
You can either install the existing package using the `python setup.py` instructions included in the readme, or install a single package from rawhide using instructions here: https://stackoverflow.com/questions/24968410/install-single-package-from-rawhide
