### ISSUE TITLE
How to build on Win10

### ISSUE THREAD

**Issue by prenfic** [BasioMeusPuga/Lector#77]
i just change my platform from macOS to win10,
and i just installed the choco (alternative to homebrew on macOS),
do find that there is no "lector" associated w/

so,
what may i do next?

**Comment by BasioMeusPuga** [comment]
* Install Python from the official website.
* Use the `pip` included with the installation to install dependencies.
* Run with `python ./__main__.py`. Adjust the path as necessary.
