### ISSUE TITLE
appimage *request

### ISSUE THREAD

**Issue by datamaskinen** [BasioMeusPuga/Lector#82]
Hi there please consider making an appimage from this... it would make it much easier for many people including you self i think

https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages

*sorry i do not know how to make this a feature request
Best regards

**Comment by BasioMeusPuga** [comment]
This is something I'm going to do with the 0.5 release. But bear in mind, I'll probably only do a flatpak image. That discussion is #5.
