### ISSUE TITLE
Please add a requirements.txt

### ISSUE THREAD

**Issue by probonopd** [BasioMeusPuga/Lector#85]
https://pip.readthedocs.io/en/1.1/requirements.html

To create a new requirements file from a known working environment, use:

`$ pip freeze > stable-req.txt`

Thank you.

**Comment by BasioMeusPuga** [comment]
Hey,

Sorry for the delay. You'll find a `requirements.txt` in the project root dir. I still haven't been able to do anything about `python-poppler-qt5` - `pip` won't even install it. I've currently left it out of the `requirements.txt` file.
