### ISSUE TITLE
Shift to PySide2 ?

### ISSUE THREAD

**Issue by khaveesh** [BasioMeusPuga/Lector#86]
Now that PySide2 has been officially accepted as the standard python-qt binding, maybe shift Lector from PyQt5 to PySide2. They are mostly compatible with each other AFAIK.

**Comment by BasioMeusPuga** [comment]
It doesn't seem as simple as substituting `PyQt5` for `PySide2` in the imports. I'm getting segfaults here. And from my understanding, there's very little advantage. Perhaps if `PyQt5` stops being maintained, or starts giving me trouble, I'll think about it.
