### ISSUE TITLE
doesn't respect desktop theme

### ISSUE THREAD

**Issue by luntik2012** [BasioMeusPuga/Lector#88]
try it with adapta-gtk-theme with xfce4 from archlinux repo

**Comment by BasioMeusPuga** [comment]
If you're running XFCE, you probably need to change the Qt theme separately. Please see if it's happening with all other Qt applications as well.

**Comment by luntik2012** [comment]
![image](https://user-images.githubusercontent.com/8270543/52557377-49876b00-2e00-11e9-8f15-66bd50d7c5ab.png)
Ok, some icons are ok, some are grey. Is it hardcoded theme on them?
Will you care about it? I can create PR

**Comment by BasioMeusPuga** [comment]
Go to Switches > Icon theme. I'm not going to change the icon theme proper, but colors are adjustable.
