### ISSUE TITLE
Expander-tree in view as table mode

### ISSUE THREAD

**Issue by 4fury** [BasioMeusPuga/Lector#93]
So easy to add many sources to the library. )

**Comment by BasioMeusPuga** [comment]
I'm sorry, you'll have to be more specific. There's already a Tree View in `Settings` that lets you add multiple sources. Is that not what you're talking about?

**Comment by 4fury** [comment]
> I'm sorry, you'll have to be more specific. There's already a Tree View in `Settings` that lets you add multiple sources. Is that not what you're talking about?

English locale. First tab - "Library". Toggle button - "View as table". Expandable folders or list of general titles instead simple book list.

**Comment by BasioMeusPuga** [comment]
That book list runs off the same model as the book cover "gallery". I'm afraid changing that would take too much effort for not a whole lot of gain. I recommend using the `Settings` dialog for multiple book sources. I might consider allowing sorting by path later.

**Comment by 4fury** [comment]
Thanks! But I see a powerful and convenient search tool. I think this is excellent replacement.
