### ISSUE TITLE
Can't open .epub files

### ISSUE THREAD

**Issue by br0nde** [BasioMeusPuga/Lector#95]
Linux br0nde 4.19.24-1-MANJARO #1 SMP PREEMPT Wed Feb 20 22:59:23 UTC 2019 x86_64 GNU/Linux
Python 3.7.2
Lector A Qt Based ebook reader v0.5.1

Lector was installed from AUR

When i trying to open epub book nothing happens

Log
2019/03/11  00:23:07,125 lector.sorter ERROR Content generation error: /home/br0nde/books/richard_k_morgan-vidoizmenennij_uglerod-1518106530.epub AttributeError Arguments: ("'NoneType' object has no attribute 'lower'",)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lector/sorter.py", line 262, in read_book
    book_breakdown = book_ref.generate_content()
  File "/usr/lib/python3.7/site-packages/lector/parsers/epub.py", line 47, in generate_content
    self.book.generate_content()
  File "/usr/lib/python3.7/site-packages/lector/readers/read_epub.py", line 351, in generate_content
    self.cover_image_name.lower() + '.jpg' in self.content[0][2].lower(),
AttributeError: 'NoneType' object has no attribute 'lower'
2019/03/11  00:23:07,218 lector.main ERROR No parseable files found

**Comment by BasioMeusPuga** [comment]
Is this happening with other books as well? If not, can you please link me to a copy of the book? I have an idea of what's going wrong, but I need the file to be able to confirm.

**Comment by br0nde** [comment]
Ok. [Link file](url=https://drive.google.com/open?id=1P5Ps7JA8CjN2gQUFyWo3SN9bDTYIMERj) 
XReader opening this epub correctly

**Comment by BasioMeusPuga** [comment]
I don't have access to the file.

**Comment by br0nde** [comment]
Sorry [try now](https://drive.google.com/file/d/1P5Ps7JA8CjN2gQUFyWo3SN9bDTYIMERj/view?usp=sharing)

**Comment by BasioMeusPuga** [comment]
This should be fixed in the latest commit. `lector-git` in the AUR.

**Comment by br0nde** [comment]
> This should be fixed in the latest commit. `lector-git` in the AUR.

Thank u very much!
