### ISSUE TITLE
Build for Windows? 

### ISSUE THREAD

**Issue by GoHoo** [BasioMeusPuga/Lector#96]
As one of the computer illiterates I'm lost here,I dont really know how to run it but I like it very much compared let's say sumatra.So it would be great to be able to run it on Windows

**Comment by BasioMeusPuga** [comment]
I'll have to look into installer frameworks for Windows. I'll let you know what I find. Give me a bit.

**Comment by GoHoo** [comment]
> I'll have to look into installer frameworks for Windows. I'll let you know what I find. Give me a bit.

An update on progress,my friend?

**Comment by BasioMeusPuga** [comment]
I'm in the middle of a lot of irl stuff right now. But as soon as I get the time, I'll be on it.

**Comment by theweavrs** [comment]
@BasioMeusPuga any update regarding Windows build?

**Comment by GoHoo** [comment]
F 
He tried but he really didn't. But hey hes doing it for free so whatever.

**Comment by smaragdus** [comment]
I will highly appreciate if [Lector](https://github.com/BasioMeusPuga/Lector) is released for Windows. Any news?

**Comment by DonaldTsang** [comment]
Same here as well @smaragdus @GoHoo @thecodrr 
Would like to request that @BasioMeusPuga to make a windows build.
